version: '3.8'

services:
  web:
    image: ${DOCKER_USERNAME}/anonywall-web:latest
    # build: . # Commented out to use pre-built image from Hub
    ports:
      - "8080:80"
    restart: always
    container_name: anonywall-web
